/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gg.view.categoriesbalances;

import gg.application.components.FieldsVisibility;
import gg.db.datamodel.Datamodel;
import gg.db.datamodel.SearchFilter;
import gg.db.entities.Category;
import gg.options.Options;
import gg.utilities.Utilities;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import org.openide.util.ImageUtilities;
import org.netbeans.api.settings.ConvertAsProperties;
import org.netbeans.swing.outline.DefaultOutlineModel;
import org.netbeans.swing.outline.OutlineModel;
import org.netbeans.swing.outline.RowModel;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.util.lookup.Lookups;
import org.openide.windows.TopComponentGroup;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//gg.view.categoriesbalances//CategoriesBalances//EN",
autostore = false)
public final class CategoriesBalancesTopComponent extends TopComponent implements LookupListener {

    private static CategoriesBalancesTopComponent instance;
    /** path to the icon used by the component and its open action */
    static final String ICON_PATH = "gg/resources/icons/CategoriesBalances.png";
    private static final String PREFERRED_ID = "CategoriesBalancesTopComponent";
    private Lookup.Result<SearchFilter> result = null;
    private List<SearchFilter> displayedSearchFilters = new ArrayList<SearchFilter>();
    /** List containing the top categories */
    private List<Category> topCategories;
    /** Map containing the sub-categories of a category */
    private Map<Category, List<Category>> subCategoriesMap = new HashMap<Category, List<Category>>();

    public CategoriesBalancesTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(CategoriesBalancesTopComponent.class, "CTL_CategoriesBalancesTopComponent"));
        setToolTipText(NbBundle.getMessage(CategoriesBalancesTopComponent.class, "HINT_CategoriesBalancesTopComponent"));
        setIcon(ImageUtilities.loadImage(ICON_PATH, true));
        putClientProperty(TopComponent.PROP_DRAGGING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);

        // Treetable settings
        outlineCategoriesBalances.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        outlineCategoriesBalances.setRootVisible(false);
        outlineCategoriesBalances.setPopupUsedFromTheCorner(false);

        // Set the supported fields
        FieldsVisibility fieldsVisibility = new FieldsVisibility();
        fieldsVisibility.setFromVisible(true);
        fieldsVisibility.setToVisible(true);
        fieldsVisibility.setByVisible(true);
        fieldsVisibility.setCurrencyVisible(true);
        fieldsVisibility.setAccountsVisible(true);
        fieldsVisibility.setCategoriesVisible(true);
        associateLookup(Lookups.singleton(fieldsVisibility));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneCategoriesBalances = new javax.swing.JScrollPane();
        outlineCategoriesBalances = new org.netbeans.swing.outline.Outline();

        jScrollPaneCategoriesBalances.setViewportView(outlineCategoriesBalances);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneCategoriesBalances, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneCategoriesBalances, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPaneCategoriesBalances;
    private org.netbeans.swing.outline.Outline outlineCategoriesBalances;
    // End of variables declaration//GEN-END:variables

    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized CategoriesBalancesTopComponent getDefault() {
        if (instance == null) {
            instance = new CategoriesBalancesTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the CategoriesBalancesTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized CategoriesBalancesTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(CategoriesBalancesTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof CategoriesBalancesTopComponent) {
            return (CategoriesBalancesTopComponent) win;
        }
        Logger.getLogger(CategoriesBalancesTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    public void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    public Object readProperties(java.util.Properties p) {
        CategoriesBalancesTopComponent singleton = CategoriesBalancesTopComponent.getDefault();
        singleton.readPropertiesImpl(p);
        return singleton;
    }

    private void readPropertiesImpl(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    @Override
    protected void componentActivated() {
        super.componentActivated();

        // Register lookup listener on the search filter top component
        result = WindowManager.getDefault().findTopComponent("SearchFilterTopComponent").getLookup().lookupResult(SearchFilter.class);
        result.addLookupListener(this);
        result.allInstances();
        resultChanged(null);

        TopComponentGroup categoriesBalancesGroup = WindowManager.getDefault().findTopComponentGroup("CategoriesBalancesGroup");
        if (categoriesBalancesGroup == null) {
            return;
        }
        categoriesBalancesGroup.open();
    }

    @Override
    protected void componentHidden() {
        super.componentHidden();

        // Remove listener on search filter top component
        result.removeLookupListener(this);
        result = null;

        TopComponentGroup categoriesBalancesGroup = WindowManager.getDefault().findTopComponentGroup("CategoriesBalancesGroup");
        if (categoriesBalancesGroup == null) {
            return;
        }
        categoriesBalancesGroup.close();
    }

    @Override
    public void resultChanged(LookupEvent ev) {
        @SuppressWarnings("unchecked")
        List<SearchFilter> searchFilters = (List<SearchFilter>) result.allInstances();
        if (!searchFilters.isEmpty() && !searchFilters.equals(displayedSearchFilters)) {
            displayData(searchFilters);
        }
    }

    /**
     * Should a category be added to the tree?<BR/>
     * A category must be added to the tree in the following cases:
     * <UL>
     * <LI>The category has been selected in the search filter window</LI>
     * <LI>The parent category of the category has been selected in the search filter window</LI>
     * <LI>A sub-category of the category has been selected in the search filter window</LI>
     * </UL>
     * @param selectedCategories List of categories that have been selected by the user in the search filter window
     * @param category Category to test (should this category be added to the tree?)
     * @return true if the category must be added into the tree, false otherwise
     */
    private boolean isCategoryToDisplay(List<Category> selectedCategories, Category category) {
        if (selectedCategories.contains(category)) {
            // If <category> has been selected in the search filter window
            return true;
        }

        for (Category selectedCategory : selectedCategories) {
            if (selectedCategory.isTopCategory() && subCategoriesMap.get(selectedCategory).contains(category)) {
                // If a sub-category of <category> has been selected in the search filter window
                return true;
            } else if (!selectedCategory.isTopCategory() &&
                    selectedCategory.getParentCategory().getId().compareTo(category.getId()) == 0) {
                // If the parent category of <category> has been selected in the search filter window
                return true;
            }
        }

        return false;
    }

    private void displayData(List<SearchFilter> searchFilters) {
        Utilities.changeCursorWaitStatus(true);

        // Load categories and sub-categories from the DB
        topCategories = Datamodel.getTopCategories(); // TODO: categories must be reloaded ONLY if a new file has been imported
        subCategoriesMap.clear();
        for (Category topCategory : topCategories) {
            List<Category> subCategories = Datamodel.getSubCategories(topCategory);
            subCategoriesMap.put(topCategory, subCategories);
        }

        // Map that contains the categories' balances by category ID and search filter
        // ((Category ID) --> (SearchFilter --> Category balance))
        Map<Long, Map<SearchFilter, BigDecimal>> categoriesBalancesMap =
                new HashMap<Long, Map<SearchFilter, BigDecimal>>();

        // Compute the sub-categories' balances (categories have always a balance of 0)
        for (SearchFilter searchFilter : searchFilters) {
            // Get all categories' balances for the current search filter
            List categoriesBalancesForCurrentSearchFilter = Datamodel.getCategoriesBalances(searchFilter);

            // For each category, add (SearchFilter --> Category balance)
            for (Object rowCategoryBalanceObject : categoriesBalancesForCurrentSearchFilter) {
                Object[] rowCategoryBalance = (Object[]) rowCategoryBalanceObject;
                Long categoryId = (Long) rowCategoryBalance[0];
                BigDecimal categoryBalance = (BigDecimal) rowCategoryBalance[1];

                // Map that contains the current category's balance for the current search filter
                // (SearchFilter --> Category balance)
                Map<SearchFilter, BigDecimal> categoryBalanceForCurrentSearchFilterMap =
                        new HashMap<SearchFilter, BigDecimal>();
                // If categories' balances have already been added for other SearchFilters
                if (categoriesBalancesMap.get(categoryId) != null) {
                    categoryBalanceForCurrentSearchFilterMap.putAll(categoriesBalancesMap.get(categoryId));
                }
                // Add the balance of the current category
                categoryBalanceForCurrentSearchFilterMap.put(searchFilter, categoryBalance);


                // Add (SearchFilter, Category balance) to the current category
                categoriesBalancesMap.put(categoryId, categoryBalanceForCurrentSearchFilterMap);
            }

            // Compute the categories' balances
            for (Category topCategory : topCategories) {
                // Initialize the category's balance
                BigDecimal topCategoryBalance = new BigDecimal(0);

                // Add the balance of each sub-category that will added to the tree
                for (Category subCategory : subCategoriesMap.get(topCategory)) {
                    // The sub-category <subCategory> will be added to the tree if:
                    // - the user didn't select any category in the search filter or
                    // - <subCategory> has been selected in the search filter,
                    //   or the parent category of <subCategory> has been selected in the search filter
                    if (!searchFilters.get(0).hasCategoriesFilter() ||
                            isCategoryToDisplay(searchFilters.get(0).getCategories(), subCategory)) {
                        Map<SearchFilter, BigDecimal> subCategoryBalanceForCurrentSearchFilterMap =
                                categoriesBalancesMap.get(subCategory.getId());
                        if (subCategoryBalanceForCurrentSearchFilterMap != null) {
                            // Get the balance of the sub-category for the current search filter
                            BigDecimal subCategoryBalance = subCategoryBalanceForCurrentSearchFilterMap.get(searchFilter);

                            // Add it to the category's balance
                            if (subCategoryBalance != null) {
                                topCategoryBalance = topCategoryBalance.add(subCategoryBalance);
                            }
                        }
                    }
                }

                // Map that contains the category's balance for the current search filter
                // (Search filter --> Category's balance)
                Map<SearchFilter, BigDecimal> topCategoryBalancesMap =
                        new HashMap<SearchFilter, BigDecimal>();
                // If categories' balances have already been added for other SearchFilters
                if (categoriesBalancesMap.get(topCategory.getId()) != null) {
                    topCategoryBalancesMap.putAll(categoriesBalancesMap.get(topCategory.getId()));
                }
                // Add the balance of the category
                topCategoryBalancesMap.put(searchFilter, topCategoryBalance);

                // Add (SearchFilter, Category balance> to the current category
                categoriesBalancesMap.put(topCategory.getId(), topCategoryBalancesMap);
            }
        }

        // Prepare the tree model
        DefaultMutableTreeNode rootNode = new DefaultMutableTreeNode(); // Root (Not displayed)

        // Add the categories and the sub-categories into the tree
        for (Category category : topCategories) {
            // Create the category <category> if:
            // - the user didn't select any category in the search filter or
            // - <category> has been selected in the search filter or
            // - a sub-category of <category> has been selected in the search filter
            if (!searchFilters.get(0).hasCategoriesFilter() ||
                    isCategoryToDisplay(searchFilters.get(0).getCategories(), category)) {

                DefaultMutableTreeNode categoryNode = new DefaultMutableTreeNode(category);

                // Add the sub-categories into the tree
                for (Category subCategory : subCategoriesMap.get(category)) {
                    // Create the sub-category <subCategory> if:
                    // - the user didn't select any category in the search filter or
                    // - <subCategory> has been selected in the search filter,
                    //   or the parent category of <subCategory> has been selected in the search filter
                    // AND
                    // - there are some balances' movements for <subCategory> or
                    //   <subCategory> has been explicitly selected in the seatch filter (in which case 0 are written)
                    if ((!searchFilters.get(0).hasCategoriesFilter() || isCategoryToDisplay(searchFilters.get(0).getCategories(), subCategory)) &&
                            (categoriesBalancesMap.get(subCategory.getId()) != null || searchFilters.get(0).getCategories().contains(subCategory))) {
                        // Add the sub-category node into the tree
                        DefaultMutableTreeNode subCategoryNode = new DefaultMutableTreeNode(subCategory);
                        categoryNode.add(subCategoryNode);
                    }
                }

                // Add the category node into the tree only if it contains sub-categories
                if (categoryNode.getChildCount() > 0) {
                    rootNode.add(categoryNode);
                }
            }
        }

        // Create the tree model based on the root
        DefaultTreeModel treeModel = new DefaultTreeModel(rootNode);

        // Create the outline model based on the tree model
        OutlineModel outlineModel = DefaultOutlineModel.createOutlineModel(
                treeModel,
                new CategoriesBalancesRowModel(searchFilters, categoriesBalancesMap),
                true,
                "Category");
        outlineCategoriesBalances.setModel(outlineModel);

        // Expand the tree
        for (int i = 0; i < rootNode.getChildCount(); i++) {
            outlineCategoriesBalances.expandPath(new TreePath(((DefaultMutableTreeNode) rootNode.getChildAt(i)).getPath()));
        }

        // Save the currently displayed list of search filters
        this.displayedSearchFilters = searchFilters;

        Utilities.changeCursorWaitStatus(false);
    }

    private class CategoriesBalancesRowModel implements RowModel {

        private List<SearchFilter> searchFilters;
        private Map<Long, Map<SearchFilter, BigDecimal>> balances;

        public CategoriesBalancesRowModel(List<SearchFilter> searchFilters, Map<Long, Map<SearchFilter, BigDecimal>> balances) {
            if (searchFilters == null) {
                throw new IllegalArgumentException("The parameter 'searchFilters' is null");
            }
            if (balances == null) {
                throw new IllegalArgumentException("The parameter 'balances' is null");
            }
            this.searchFilters = searchFilters;
            this.balances = balances;
        }

        @Override
        public Class getColumnClass(int column) {
            return String.class;
        }

        @Override
        public int getColumnCount() {
            return searchFilters.size();
        }

        @Override
        public String getColumnName(int column) {
            return searchFilters.get(column).getPeriod().toString();
        }

        @Override
        public Object getValueFor(Object node, int column) {
            Object nodeInfo = ((DefaultMutableTreeNode) node).getUserObject();

            if (nodeInfo != null) {
                Category category = (Category) nodeInfo;
                SearchFilter searchFilter = searchFilters.get(column);

                Map<SearchFilter, BigDecimal> categoryBalances = balances.get(category.getId());
                if (categoryBalances != null) {
                    BigDecimal categoryBalanceSearchFilter = categoryBalances.get(searchFilter);
                    if (categoryBalanceSearchFilter != null) {
                        return Utilities.getSignedBalance(categoryBalanceSearchFilter);
                    }
                }

                if (Options.displayZero()) {
                    return Utilities.getSignedBalance(BigDecimal.ZERO);
                } else {
                    return "";
                }
            }
            return null;
        }

        @Override
        public boolean isCellEditable(Object node, int column) {
            return false;
        }

        @Override
        public void setValueFor(Object node, int column, Object value) {
        }
    }
}
